export enum ExpenseCategory {
  TRAVEL = 'TRAVEL',
  HOTEL = 'HOTEL',
  RESTAURANT = 'RESTAURANT',
  TRANSPORT = 'TRANSPORT',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  TEAM_EVENT = 'TEAM_EVENT',
  OTHER = 'OTHER',
}
